In [29]:
import pandas as pd
import numpy as np
import os
import joblib

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

from scipy import sparse

In [30]:
project_path="/content/drive/MyDrive/AI-Career-Assistant"


data_path=os.path.join(
    project_path,
    "data/processed/clean_resume.csv"
)


df=pd.read_csv(data_path)


df.head()

                 Category                                       Clean_Resume
0      Operations Manager  key competency multi operation management peop...
1                  Hadoop  skill set hadoop map reduce hdfs hive sqoop ja...
2        Business Analyst  skill area exposure modeling tool bizagi ms vi...
3          Civil Engineer  education detail b.e civil engineering civil e...
4  Electrical Engineering  education detail july 2016 may 2019 electrical...

In [31]:
print(df.shape)

(166, 2)

In [32]:
df["Category"].value_counts()

Category
Java Developer               13
Database                     11
Data Science                 10
HR                           10
Advocate                     10
Testing                       7
Hadoop                        7
DotNet Developer              7
Automation Testing            7
DevOps Engineer               7
Python Developer              6
Arts                          6
SAP Developer                 6
Business Analyst              6
Health and fitness            6
Civil Engineer                6
Electrical Engineering        5
Sales                         5
Mechanical Engineer           5
ETL Developer                 5
Network Security Engineer     5
Blockchain                    5
Operations Manager            4
Web Designing                 4
PMO                           3
Name: count, dtype: int64

In [33]:
df=df.dropna()


df=df.drop_duplicates()


print(df.shape)

(166, 2)

In [34]:
X=df["Clean_Resume"]

y=df["Category"]

In [35]:
X_train_text, X_test_text, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.2,

    random_state=42,

    stratify=y

)

In [36]:
tfidf=TfidfVectorizer(

    max_features=50000,

    ngram_range=(1,3),

    min_df=1,

    max_df=0.98,

    sublinear_tf=True,

    stop_words="english"

)

In [37]:
X_train=tfidf.fit_transform(
    X_train_text
)


X_test=tfidf.transform(
    X_test_text
)

In [38]:
print(X_train.shape)
print(X_test.shape)

(132, 50000)
(34, 50000)

In [40]:
model_path=os.path.join(
    project_path,
    "models"
)


os.makedirs(
    model_path,
    exist_ok=True
)

In [41]:
sparse.save_npz(

    model_path+"/X_train.npz",

    X_train

)


sparse.save_npz(

    model_path+"/X_test.npz",

    X_test

)

In [42]:
pd.DataFrame(
    y_train
).to_csv(

    model_path+"/y_train.csv",

    index=False

)


pd.DataFrame(
    y_test
).to_csv(

    model_path+"/y_test.csv",

    index=False

)

In [43]:
joblib.dump(

    tfidf,

    model_path+"/tfidf_vectorizer.pkl"

)

['/content/drive/MyDrive/AI-Career-Assistant/models/tfidf_vectorizer.pkl']